spring:
  main:
    allow-circular-references: true
  application:
    name: com.dentalcare.g5.main
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true

server:
  port: ${PORT}
  base: g5/api
  version: v1

jwt:
  secret: ${JWT_SECRET}

my:
  template:
    default: error.ftlh

cors:
  allowed-origins:
    - "http://localhost:4200"
    - "http://localhost:3000"
    - "http://localhost:8080"